### ISSUE TITLE
dig throws error

### ISSUE THREAD

**Issue by hunsheridan** [IntellexApps/blcheck#3]
Hey!

Firstly, thank you for maintaining this awesome tool... it saves me a hell of a hard time...

Lately I've been seeing this (ever since the update of 17th this month i believe):

 [ \ 100% ] checking...    1 / 1  /usr/bin/dig: '81.200.248.178.0spam-killlist.fusionzero.com\n0spam.fusionzero.com\naccess.redhawk.org\nall.rbl.jp\nall.spam-rbl.fr\nall.spamrats.com\naspews.ext.sorbs.net\nb.barracudacentral.org\nbackscatter.spameatingmonkey.net\nbadnets.spameatingmonkey.net\nbb.barracudacentral.org\nbl.drmx.org\nbl.konstant.no\nbl.nszones.com\nbl.spamcannibal.org\nbl.spameatingmonkey.net\nbl.spamstinks.com\nblack.junkemailfilter.com\nblackholes.five-ten-sg.com\nblacklist.sci.kun.nl\nblacklist.woody.ch\nbogons.cymru.com\nbsb.empty.us\nbsb.spamlookup.net\ncart00ney.surriel.com\ncbl.abuseat.org\ncbl.anti-spam.org.cn\ncblless.anti-spam.org.cn\ncblplus.anti-spam.org.cn\ncdl.anti-spam.org.cn\ncidr.bl.mcafee.com\ncombined.rbl.msrbl.net\ndb.wpbl.info\ndev.null.dk\ndialups.visi.com\ndnsbl-0.uceprotect.net\ndnsbl-1.uceprotect.net\ndnsbl-2.uceprotect.net\ndnsbl-3.uceprotect.net\ndnsbl.anticaptcha.net\ndnsbl.aspnet.hu\ndnsbl.inps.de\ndnsbl.justspam.org\ndnsbl.kempt.net\ndnsbl.madavi.de\ndnsbl.rizon.net\ndnsbl.rv-soft.info\ndnsbl.rymsho.ru\ndnsbl.sorb' is not a legal name (ran out of space)

and that's it nothing else is done...

system is Centos 7, fully upgraded...

Cheers!

**Comment by hunsheridan** [comment]
For me this solved the problem (note the -e after echo):

`351c351
<                 BLACKLISTS=$(echo "$BLACKLISTS\n$DOMAIN")
---
>                 BLACKLISTS=$(echo -e "$BLACKLISTS\n$DOMAIN")
`

**Comment by IntellexApps** [comment]
Seems like a legit fix :)

thx!
